#!/bin/bash
# Wrapper to call pgbackrest inside docker container
# Usage: same as pgbackrest CLI

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR/.." && docker compose -p pginventory exec -T -u postgres pgbackrest-client pgbackrest "$@"
