syntax = "proto3";
package extractor.v1;
option go_package = "github.com/robert-sjoblom/pg-inventory/gen/extractor/v1;extractorv1";

service ExtractorService {
    rpc ListDatabases(ListDatabasesRequest) returns (ListDatabasesResponse);
    rpc ListBackups(ListBackupsRequest) returns (ListBackupsResponse);
}

message ListDatabasesRequest {}
message ListDatabasesResponse {
    repeated Database databases = 1;
}
message ListBackupsRequest {}
message ListBackupsResponse {
    string stanza = 1;
    repeated BackupInfo backups = 2;
}

message Database {
    string name = 1;
    uint32 oid = 2;
}

message BackupInfo {
    string label = 1;
    string type = 2;
    int64 timestamp_start = 3;
    int64 timestamp_stop = 4;
    uint64 backup_size = 5;
    uint64 repo_size = 6;
    string database_version = 7;
    bool error = 8;
    uint32 repo_key = 9;
}